name = "codeium-quoting-tool"
compatibility_date = "2024-01-08"
compatibility_flags = ["nodejs_compat"]
main = "./functions/[[path]].js"
pages_build_output_dir = "dist"

[vars]
FLASK_SECRET_KEY = ""  # Will be set via wrangler secret
