name = "codeium-quoting-tool"
compatibility_date = "2024-01-08"
compatibility_flags = ["nodejs_compat"]

[build]
command = ""

[site]
bucket = "./public"

[[routes]]
pattern = "/api/*"
script = "api/[[route]].js"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

[vars]
FLASK_SECRET_KEY = ""  # Will be set via wrangler secret
