name = "codeium-quoting-tool"
compatibility_date = "2024-01-08"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "."
include = ["*.html", "*.css", "*.js"]

[build]
command = ""

[pages]
pages_build_output_dir = "public"
