name = "codeium-quoting-tool"
compatibility_date = "2024-01-08"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pip install -r requirements.txt && python build.py"

[site]
bucket = "./dist"

[env.production]
name = "codeium-quoting-tool-prod"

[vars]
FLASK_SECRET_KEY = ""  # Will be set via wrangler secret
